CREATE OR REPLACE PACKAGE HR_PACKAGE AS 
    PROCEDURE prGetEmployees(p_rc OUT SYS_REFCURSOR);
END HR_PACKAGE;
/


CREATE OR REPLACE PACKAGE BODY HR_PACKAGE AS

  PROCEDURE prGetEmployees(p_rc OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN p_rc FOR
        SELECT * FROM EMPLOYEES ORDER BY EMPLOYEE_ID;
  END prGetEmployees;

END HR_PACKAGE;
/
